// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGHexBH5avdbHzVZDoE-YoXLY3izwfdlU',
    appId: '1:60848340645:web:0b48c96b8c6d724254d74c',
    messagingSenderId: '60848340645',
    projectId: 'myapp-6cbbf',
    authDomain: 'myapp-6cbbf.firebaseapp.com',
    storageBucket: 'myapp-6cbbf.firebasestorage.app',
    measurementId: 'G-J4NZ6THHY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeTJMQopCMsvCVaGKRAdFLl-PEPCK76Mo',
    appId: '1:60848340645:android:62e624472ba5986254d74c',
    messagingSenderId: '60848340645',
    projectId: 'myapp-6cbbf',
    storageBucket: 'myapp-6cbbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY3I0M_SJdm_oHhQflue_l1DsrlvZjfBU',
    appId: '1:60848340645:ios:91d39aa7eb47385554d74c',
    messagingSenderId: '60848340645',
    projectId: 'myapp-6cbbf',
    storageBucket: 'myapp-6cbbf.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY3I0M_SJdm_oHhQflue_l1DsrlvZjfBU',
    appId: '1:60848340645:ios:91d39aa7eb47385554d74c',
    messagingSenderId: '60848340645',
    projectId: 'myapp-6cbbf',
    storageBucket: 'myapp-6cbbf.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGHexBH5avdbHzVZDoE-YoXLY3izwfdlU',
    appId: '1:60848340645:web:0b48c96b8c6d724254d74c',
    messagingSenderId: '60848340645',
    projectId: 'myapp-6cbbf',
    authDomain: 'myapp-6cbbf.firebaseapp.com',
    storageBucket: 'myapp-6cbbf.firebasestorage.app',
    measurementId: 'G-J4NZ6THHY5',
  );
}
